# Generated by Django 4.2.7 on 2023-11-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='movies',
            new_name='livros',
        ),
    ]
